### ISSUE TITLE
Simplistic filtering of headings in comment body

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel-github#104]
This code is a bit too simplistic:

https://github.com/sopel-irc/sopel-github/blob/bb66e621512673dc446bb7801572a76301b190ec/sopel_modules/github/formatting.py#L83

It doesn't allow for one-line comments that start with an issue/PR/discussion reference, like [this one I just left](https://github.com/sopel-irc/sopel/issues/1683#issuecomment-1035864475) in Sopel's main repo.

**Comment by Exirel** [comment]
I think `and not all(l == '#' for l in line)` should do the trick.

**Comment by dgw** [comment]
Might want to think again. Markdown headings, like what we use in the issue templates for Sopel itself, are:

```markdown
# Heading 1
## Heading 2
### Heading 3

And so on.
```

The whole line won't be just `#` characters. But it _could_ work to check if `line.split(' ', maxsplit=1)[0]` is all `#`s, since Markdown headings are required to have a space between the `#` and the heading text.
