### ISSUE TITLE
Only the last of multiple GitHub URLs is processed (sometimes)

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel-github#13]
If someone sends multiple issue URLs in one line:

```
<dgw> https://github.com/ircv3/ircv3-ideas/issues/33
      https://github.com/ircv3/ircv3-ideas/issues/32
```

only the last one is processed:

```
<Sopel> [GitHub] [ircv3/ircv3-ideas #32] jesopo: Content warnings | I'd like to propose
        using a `message-tag` on a `PRIVMSG` to denote a message with a content warning. …
```

The rest are simply ignored.

Things get more interesting when both issue/PR and commit URLs are sent in the same line: The last match for each will be processed.

Each `@rule` decorator can match only once, so it makes sense that the module works this way.

This issue is probably specific to Sopel instances with the core `url` module disabled, like mine. All the `url_callbacks` stuff appears to be registered properly for when `url` is loaded.

It's probably not worth fixing this separately (with tweaks to the regex patterns or whatever). Until sopel-irc/sopel#1489 is fixed, the easiest and best solution—using `@url` instead of `@rule`—would break this module's URL-processing on instances that do not load the core `url` module.

We should probably just note that the issue exists, and fix it once and for all when the `@url` decorator is fixed to work properly in all cases.

**Comment by Exirel** [comment]
Hello @dgw I think this will be fixed for Sopel 7.x! Have fun.
