### ISSUE TITLE
Can't load on new Sopel setup

### ISSUE THREAD

**Issue by GideonWolfe** [sopel-irc/sopel-github#56]
Not sure if I'm doing something wrong, but I'm running sopel in docker. I added this package to the list to automatically download, which it does.

Then in a buffer with sopel I run `.load github` and I am presented with 

```
SyntaxError: invalid syntax (file "/home/sopel/.local/bin/python3.6/site-packages/sopel_modules/github/webhook.py, line 167)
```

I'm not doing anything with webhooks, would just like to query the occasional repo...

**Comment by dgw** [comment]
That doesn't make sense. Line 167 is bog-standard Python, syntactically equivalent to the line above it. https://github.com/sopel-irc/sopel-github/blob/08a816af92f52793349a07c99af3b941eac4dfb8/sopel_modules/github/webhook.py#L167

@HumorBaby Any insights, given this is happening with Docker?

@GideonWolfe What version of the Sopel Docker image are you using, and what version of sopel-github is it loading?

**Comment by dgw** [comment]
Ack, it was the line above that. Should be fixed by 23a3a283010a8244d9b37c343e24145ea58ee952 / 0.2.6 (publishing momentarily).

**Comment by dgw** [comment]
Verified that the latest release (0.2.6) loads without errors on the "official" Sopel instance in our freenode channel. If this issue is not actually resolved, feel free to reopen with further details!

**Comment by GideonWolfe** [comment]
Works great now, thanks for the quick fix!

**Comment by dgw** [comment]
Thank you for letting me know there was a problem!
