### ISSUE TITLE
OAuth client_id and client_secret method deprecated

### ISSUE THREAD

**Issue by Operator873** [sopel-irc/sopel-github#60]
Receiving notifications from GitHub that authentication method of using client_id and client_secret is deprecated. Using personal tokens via Basic Authentication is the recommend route to authentication.

From [Blog Post](https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/)

Authenticating using query parameters
GitHub is deprecating authentication to the GitHub API using query parameters, such as using a access_token query parameter for OAuth user authentication or a client_id/client_secret query parameter for OAuth application authentication. All authentication to the GitHub API should be done using HTTP basic authentication.

**Comment by dgw** [comment]
Yep, I talked about this in our IRC channel earlier this week. Waiting on a reply from GitHub support to find out if we can keep using the current app credentials via HTTP Basic Auth instead of query params, or need to uproot everyone and switch to tokens.

**Comment by Operator873** [comment]
Sorry I missed the talk. >.< Thanks dgw

**Comment by dgw** [comment]
Nah, no problem. We might as well have an issue tracking this for the milestone!

**Comment by dgw** [comment]
Still waiting for a reply from GitHub support… This is the fourth business day since I submitted the ticket. Not encouraging, is it? 🙁

**Comment by dgw** [comment]
I gave them a full week, and nothing, despite confirmation from Twitter support (_days_ ago) that my ticket was received and I'd hear back soon. So, we're going to move forward anyway with #62 and figure out what to do later if it turns out to be the wrong choice.

@Operator873 Want to smoke test that change with me?
