### ISSUE TITLE
IRC message output should expose abbreviated commit checksum

### ISSUE THREAD

**Issue by cottongin** [sopel-irc/sopel-github#71]
Current output:
```
15:59:36 <Sopel> [sopel] lgtm-com[bot] commented on pull request #1904: This pull request **introduces 1 alert** when
                 merging 3c3518032f0e9ca858e597d5c0691ea3a229b2db into ee3fcb2ab8cfea3e08f8cc9b3997f2ba32fa5494
                 - [view on LGTM.com](https://lgtm.com/projects/g/sopel- […] https://git.io/JJKrs
```

Desired output (or something similar):
```
15:59:36 <Sopel> [sopel] lgtm-com[bot] commented on pull request #1904: This pull request **introduces 1 alert** when
                 merging 3c35180… into ee3fcb2… - [view on LGTM.com](https://lgtm.com/projects/g/sopel- […]
                 https://git.io/JJKrs
```

Realizing it's not as simple as it sounds perhaps, but would be nice.

**Edit**: This would also free up some not-insignificant amount of characters for additional, more useful, output, while staying under the RFC-spec 512 bytes per line limit.

**Comment by dgw** [comment]
Hmm. Would also be nice to have some solution to avoid truncating URLs in that way. Separate issue, that, but it's still awful.

Detecting commit hashes isn't that hard, really. `[0-9a-f]{40}` would match the annoying full hashes, while leaving already-abbreviated hashes alone.
