### ISSUE TITLE
GH topic links handled improperly

### ISSUE THREAD

**Issue by half-duplex** [sopel-irc/sopel-github#96]
```irc
22:11:37 < xnaas> ... https://github.com/topics/sopel-plugin ...
22:11:37 <+Sopel> [GitHub] Not Found
```

I suspect it's parsing the [topic link](https://github.com/topics/sopel-plugin) as a project link, user=topics repo=sopel-plugin

**Comment by dgw** [comment]
No doubt. Same would happen for events, collections, and other tabs shown across the top of https://github.com/topics

Might as well include all of those in the scope of this issue and fix them all at once.
